export { HeroSection } from "./HeroSection";
export { AboutSection } from "./AboutSection";
export { ServicesSection } from "./ServicesSection";
export { WhyWorkWithMeSection } from "./WhyWorkWithMeSection";
export { TestimonialsSection } from "./TestimonialsSection";
export { FreeResourcesSection } from "./FreeResourcesSection";
export { FinalCTASection } from "./FinalCTASection";
export { FAQSection } from "./FaqSection";
export { EventsGallery } from "./EventsGallery";
